services:
  - type: web
    name: buildmart-backend
    env: node
    plan: free
    buildCommand: npm install -g pnpm && cd /opt/render/project/src && pnpm install && pnpm --filter @dtc/backend build
    startCommand: pnpm start
    rootDir: apps/backend
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_Mi07QOaLcCHu@ep-soft-feather-av9wiizj-pooler.c-11.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: JWT_SECRET
        value: supersecretjwtkey
      - key: COOKIE_SECRET
        value: supersecretcookiekey
      - key: STORE_CORS
        value: "*"
      - key: ADMIN_CORS
        value: "*"
      - key: AUTH_CORS
        value: "*"
